name: Setup rust environment

runs:
  using: "composite"
  steps:
    - name: Install rustfmt, clippy, llvm-tools
      id: rust-toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy, llvm-tools

    - name: Generate lockfile
      shell: bash
      run: cargo generate-lockfile

    - name: Cache cargo registry
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: rust-${{ steps.rust-toolchain.outputs.cachekey }}
        shared-key: qrs.rust
    
    - name: Install llvm-cov
      shell: bash
      run: cargo install cargo-llvm-cov
