[package]
name = "rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
exclude.workspace = true

[dependencies]
chrono = { workspace = true }
chrono-tz = { workspace = true }
