name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install nextest
      shell: bash
      run: |
        curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - name: Build
      run: cargo build --verbose -r --workspace
    - name: Run tests
      run: cargo nextest run -r --workspace --verbose --retries 1

  coverage:
    needs: ci-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: llvm-tools-preview
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: taiki-e/install-action@nextest
    - name: Collect coverage data (including doctests)
      run: |
        cargo llvm-cov --no-report nextest
        cargo llvm-cov --no-report --doc
        cargo llvm-cov report --doctests --lcov --output-path lcov.info
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
