name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@nextest
    - run: cargo nextest run -r --workspace

  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: llvm-tools-preview
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: taiki-e/install-action@nextest
    - run: |
        cargo llvm-cov --no-report nextest
        cargo llvm-cov --no-report --doc
        cargo llvm-cov report --doctests --lcov --output-path lcov.info --ignore-filename-regex scripts/*
    - uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
