name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: rustup component add rustfmt
    - run: rustup component add clippy

    - uses: Swatinem/rust-cache@v2
    - run: cargo check --all --all-features
    - run: cargo fmt --all --all-features -- --check
    - run: cargo clippy --all-targets --all-features -- -D warnings
        
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test --release --all-features
    
