name: Rust

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - run: cargo check --all --all-features
    - run: cargo fmt --all --check --verbose
    - run: cargo clippy --all-features -- -D warnings
        
  test:
    needs: check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - run: cargo test --release --all-features

  post:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        git fetch
        git checkout ci_passed
    - run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git remote set-url origin https://${{ secrets.PAT }}@github.com/sugaim/qrs.git

    - run: sudo apt install cloc
    - run: cloc --exclude-list-file=.gitignore . > .measurements/cloc.txt

    - run: git add .
    - run: git commit -m "ci passed"
    - run: git push
