name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2

    - run: cargo check --all --all-features
    - run: cargo fmt --all --check --verbose
    - run: cargo clippy --all-features -- -D warnings
        
  test:
    needs: check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    
    - run: cargo test --release --all-features
    
